// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG8s32NW2jTLfKLvnM5TXcpItZsVkh36U',
    appId: '1:976358883124:web:2c01980d0765f04236ef61',
    messagingSenderId: '976358883124',
    projectId: 'flutteryapita',
    authDomain: 'flutteryapita.firebaseapp.com',
    storageBucket: 'flutteryapita.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq0lAsSzuqJQ1--Hss9fZudYajrt4Gr4w',
    appId: '1:976358883124:android:418b379849807de436ef61',
    messagingSenderId: '976358883124',
    projectId: 'flutteryapita',
    storageBucket: 'flutteryapita.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF3iTguXLOr7JKEA4RKDTaVrckK6PD--I',
    appId: '1:976358883124:ios:6cf29d32d796017236ef61',
    messagingSenderId: '976358883124',
    projectId: 'flutteryapita',
    storageBucket: 'flutteryapita.firebasestorage.app',
    iosClientId: '976358883124-49fjf0qtr9amulivvdhu7b061gm053rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.nuevoyapita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF3iTguXLOr7JKEA4RKDTaVrckK6PD--I',
    appId: '1:976358883124:ios:6cf29d32d796017236ef61',
    messagingSenderId: '976358883124',
    projectId: 'flutteryapita',
    storageBucket: 'flutteryapita.firebasestorage.app',
    iosClientId: '976358883124-49fjf0qtr9amulivvdhu7b061gm053rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.nuevoyapita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG8s32NW2jTLfKLvnM5TXcpItZsVkh36U',
    appId: '1:976358883124:web:187773d34d705ba336ef61',
    messagingSenderId: '976358883124',
    projectId: 'flutteryapita',
    authDomain: 'flutteryapita.firebaseapp.com',
    storageBucket: 'flutteryapita.firebasestorage.app',
  );
}
